### ISSUE TITLE
Validation for MasterCard BIN 2-Series (222100-272099)

### ISSUE THREAD

**Issue by afixibiranchi** [JamesEggers1/node-luhn#13]
The luhn test is failing for the MasterCard BIN 2-Series (222100-272099). 
Please update the luhn code to accomodate BIN 2 series.

**Comment by JamesEggers1** [comment]
I'll work on getting this updated.  Have you seen any test numbers associated with the new 2-Series?

**Comment by JamesEggers1** [comment]
Test card number 2221000010000015 appears to be validating properly.  If there is a different test card number, please provide so i can verify against it.

**Comment by JamesEggers1** [comment]
Closing as 222-series cards appear to be validating properly and no additional test cards have been provided.
