### ISSUE TITLE
Return true when the card number is zero, wtf ?

### ISSUE THREAD

**Issue by Masterchoc** [JamesEggers1/node-luhn#14]
As in the title, the function returns true with a card number of zero, (or multiple zeros).

I dont know what to think, it look like a major issue.

I didnt search further in the library code to find a solution yet, but soon i'll try.

**Comment by JamesEggers1** [comment]
This issue is how the checksums are calculated.  Since the validation algorithm adds the digits and multiples of the digits together and then checks that it's divisible by 10, a sum of 0 would pass the validation.

I'll add tests and a validation to test that the summation of algorithm isn't 0.

**Comment by JamesEggers1** [comment]
This is now fixed in v2.3.0 of the package.
