### ISSUE TITLE
Strange usage

### ISSUE THREAD

**Issue by LinusU** [JamesEggers1/node-luhn#3]
Hi,

When using this module from Node.js it feels very strange to do `require('luhn').luhn`. All the other libraries is just `require('name')`.

Please allow the following code to work:
```
var luhn = require('luhn');

luhn.validate('123456');
```

**Comment by JamesEggers1** [comment]
Been really behind and finally getting around to this.  This will be a part of v1.1 or v2 shortly as there are other items changes coming with the client-side aspect of things too.

**Comment by JamesEggers1** [comment]
Updated package to v2.0.0 which addresses this.  The usage is now as follows:

```
var luhn = require("luhn");
var is_valid = luhn.validate("number");
```
