### ISSUE TITLE
Rounding problem for numbers > 2^53 (15.9 decimal digits)

### ISSUE THREAD

**Issue by thedewi** [JamesEggers1/node-luhn#8]
Javascript numbers cannot represent every integer above 2^53 (15.9 decimal digits), but credit card numbers can be up to 19 digits. This can give the rightmost moduli a rounding error.

Fortunately, most payment gateways only take up to 16 digits, and as far as I know no valid numbers begin with 9, so this only will only affect rare 17-19 digit card numbers. But it confused me when I hit it. :)

Problem example (Laser test number): 6304985028090561515    [% 10 == 6]

**Comment by JamesEggers1** [comment]
This is something I will keep open to review additional card holders and see how the algorithm will need to change.

However, at the moment, I'm going to make this a lower priority since Laser Card Services is no longer active per the company's website - http://www.ipso.ie/section/LaserCardServicesLtd.

**Comment by thedewi** [comment]
Yeah, I'm not aware of any current services either. There may be no practical impact. I think it's more a source of confusion / failing tests.

**Comment by JamesEggers1** [comment]
I'm getting ready to push a v2.0 version of the module to clean up the interface and change the custom client-side aspect of it to use Bower.  Along with that push I'll be expanding the tests to include more tests.  In the event that I can bring in the Laser Card example (or similar one) I'll make sure to update this issue and close it.

**Comment by JamesEggers1** [comment]
I'm testing out a few Big Number packages in order to understand how to use potentially integrate them into the algorithm.  This is an issue and edgecase but it's also one I want to try and fix.  Look for a solution soon and I'll post back here once it's implemented.

**Comment by JamesEggers1** [comment]
Resolved in v2.1 of the package thanks to Jhericks.
