### ISSUE TITLE
Version 2.0 provides "can't find variable: module" error

### ISSUE THREAD

**Issue by tomaszlabacki** [JamesEggers1/node-luhn#9]
Hi guys,
after upgrade to 2.0 we have **ReferenceError: Can't find variable: module** problem during karma testing phase. 

Some logs:

```
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket Ffl1DeLaMFIXy6QgbOeu with id 66221296
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: module
  at /tmp/app/target/main/6a26ec8/js/lib.js:1255
```

We solved this by using version "c521434489d38fe561667f26ca2616c8e7e430a3" (unfortunately there is no tags in repo) in our bower.json, but it would be nice to have the lastest one ;)

**Comment by JamesEggers1** [comment]
This was an issue associated with a bug in the minified version.  This has been corrected in version 2.2 and later.
